### ISSUE TITLE
Few issues with readme

### ISSUE THREAD

**Issue by birdybro** [ArcadeTV/msu-md-sonic#1]
1. CRC32: AFE05EEE matching version of Sonic is actually "Sonic the Hedgehog (Japan, Europe, Korea)" (https://datomatic.no-intro.org/index.php?page=show_record&s=32&n=1230). It's a version that wasn't technically released across the world. The name scheme in the readme is likely from old romsites which may have limited days, so using the new No-Intro naming scheme probably would be better.
2. ~~Instructions are unclear as to how to get the ips patch, unless this is prior to it's release, which isn't clear if that is the case.~~ Forget I mentioned this, releases is always so hidden in github I barely notice it :P
3. Report issues here section seems to be pointing at a different repo, is that intended?

**Comment by ArcadeTV** [comment]
Thanks for this! Yes, I used the first rom as source that popped up on my hdd, you're totally right by mentioning this.
I have changed the source ROM to the no-Intro release:

* Sonic The Hedgehog (USA, Europe).md (CRC F9394E97)

I will also correct the readme to point to this repo.
Thanks again, that was a great feedback!

**Comment by ArcadeTV** [comment]
All done plus I released v1.0
https://github.com/ArcadeTV/msu-md-sonic/releases/tag/v1.0

Thanks again!
