### ISSUE TITLE
Doesn't boot on MiSTer

### ISSUE THREAD

**Issue by Chocobobobo** [ArcadeTV/msu-md-sonic#5]
**Patch version**
Yes, 1.3

**Platform**
MiSTer
**Describe the bug**
Game doesn't load. Either when following your instructions, or by renaming *.md to cart.rom
Just going straight to the CD audio UI.

**Additional context**

**Comment by ArcadeTV** [comment]
Are you getting this with other games too?
Is your sega cd bios set up?
Is your .cue file and soundPack present in the same folder?
Unfortunately I have no clue how to set this up on mister. I've heared people had issues when they released a new fw or update not long ago.
Also there may be another option that needs to be enabled but I'm not sure about it.

**Comment by SwedishGojira** [comment]
There must be a user error here. It is working fine for me on my MiSTer in the latest version of MegaCD core.

I do know however that there is a MSU-MD pack on a certain archive page that include this hack and that one have an incorrectly renamed files so the game will not boot. Don't know if it is related or not.

**Comment by ArcadeTV** [comment]
@Chocobobobo is it working for you after you renamed the files accordingly?

@SwedishGojira Thanks for the hint! Would you be able to give a briefdescription of what is needed on mister to play these? I would add a wiki page about setting things up on mister. Thanks again!

**Comment by Chocobobobo** [comment]
@SwedishGojira  Thanks for the hint. What are the names of the files you have in your folder exactly? Thanks.

**Comment by ArcadeTV** [comment]
> What are the names of the files you have in your folder exactly? 

As long as the .md and .cue have the same filename it'll be alright. Just copy the filename (without extension) to the other.
